### ISSUE TITLE
Exercise 1.3: JavaScript Basics Part 2

### ISSUE THREAD

**Issue by rmoise** [rmoise/simple-js-app#2]
### Part 1

- [x] Below the `pokemonList` array in your “scripts.js” file, create a `for` loop that iterates over each item in `pokemonList`:

- [x] Use `document.write()` inside the loop’s code to write the Pokémon name on your website’s DOM.

- [x] Use what you’ve learned about adding strings in JavaScript to write the Pokémon’s height next to its name, for example, “Bulbasaur (height: 7)”.

### Part 2

- [x] You should now be able to open the “index.html” of your project in the browser and see a list of Pokémon appear. Work with the inspector and JavaScript console of your Developer Tools to see if there are any errors in your code. You can also use the Web Inspector to adjust your CSS and make things look nicer.

### Part 3

- [x] Next, add code to highlight special Pokémon in your list. Be sure to keep adding comments to explain and document what your code does. Within the loop, add a conditional. The conditional should check if the height is above a certain value (you’re free to pick whatever value you want). If it is, add the note “Wow, that’s big!” to the output. Make sure you set up the conditional so that only one Pokémon has the label “Wow, that’s big!” It could, for example, look like this: “Bulbasaur (height: 7) - Wow, that’s big!”. For example, if you had the following array:

![Image](https://user-images.githubusercontent.com/9626657/188569361-6875d617-5889-4203-8628-d26b6f2d6633.png)

And the threshold value were `1.0`, you'd get something like this:

![Image](https://user-images.githubusercontent.com/9626657/188569534-541be23b-16c4-4686-8c2d-6539456be2e3.png)

### Part 4

- [x] Save the changes, then commit and push them to your GitHub repository. Submit the link to your GitHub repository here. Feel free to share additional thoughts or ask questions on your submission page.
