### ISSUE TITLE
Exercise 1.4: JavaScript Functions Part 1

### ISSUE THREAD

**Issue by rmoise** [rmoise/simple-js-app#3]
### Part 1

- [ ] Open this [Calculator repl](https://repl.it/@CFCurriculum/CalculatorTaskPart1) by opening it in your browser and and click on the fork button so you can have a copy of the code that you can modify. (After you click fork, the repl provided becomes your repl and you can make the necessary changes. After modification, you can share your repl link from your browser's address/search bar.)

![Image](https://user-images.githubusercontent.com/9626657/188570271-7562db0c-cb35-4846-a3b4-bcd6d58ca8e8.png)

### Part 2

- [ ] 1. Create the following four functions inside your new copy of the Calculator repl (make sure you put your code in the “JavaScript” window!). Each function will perform a specific mathematical operation on two numbers (which will be the function’s parameters). Make sure your functions have the exact same function names listed below; otherwise, your code won't work. When naming the parameters, however, feel free to choose whatever names you’d like (though we recommend keeping them consistent):

  * An **add function:** this should add two numbers (parameters) and return the sum.
  * A **subtract function:** this should subtract the second number from the first number and return the difference.
  * A **multiply function:** this should multiply two numbers and return the product.
  * A **divide function:** this should divide the first number by the second number and return the quotient; however, if the divisor is equal to zero, the function should return the text “Not Allowed.”

- [ ] 2. Save your repl and submit the link here for your Tutor to review.

**Comment by raheebwa** [comment]
Hey @rmoise feel free to also attach links to the completed
 projects here

**Comment by rmoise** [comment]
Ah good point! Will do

**Comment by rmoise** [comment]
https://replit.com/@rmoise/CalculatorTaskPart1#script.js
