### ISSUE TITLE
Exercise 1.5: JavaScript Functions Part 2

### ISSUE THREAD

**Issue by rmoise** [rmoise/simple-js-app#4]
### Part 1: `forEach()` Loops

- [ ] Use a `forEach()` function instead of the `for` loop you have to iterate over the Pokémon in your `pokemonList` array in order to print the details of each one. We recommend revisiting and carefully studying the `userList` example in this Exercise before doing this part of the task. Commit and push the changes to your GitHub repository.

### Part 2: IIFE

- [ ] 1. In the “scripts.js” file of your project, wrap your `pokemonList` array in an IIFE to avoid accidentally accessing the global state.
- [ ] 2. Before anything else, create a new `pokemonRepository` variable to hold what your IIFE will return, then assign the IIFE to that variable.

- [ ] 3. The IIFE should `return` an object with the following public functions assigned as keys:
  * getAll: return all items (`pokemonRepository.getAll();` should return the `pokemonList` array)
  * `add:` add a single item to the `pokemonList` array (calling `pokemonRepository.add(item);` should add the Pokémon referred to with item to the `pokemonList` array)

- [ ] 4. Make sure both functions are defined separately with the `function` keyword. Also, the IIFE returns only an object with the same names for keys as values (see the last paragraph of the Exercise)

- [ ] 5. Outside of and below the IIFE, you should already have a `forEach()` loop that iterates over each Pokémon in the repository. But since you’ve limited access to the `pokemonList` array that’s inside the IIFE (so that it’s only accessible through one of the two functions returned by the IIFE), you need to update the loop code to cope with the new changes. Essentially, you need to use one of the two functions returned by the IIFE in order to retrieve the `pokemonList` array.

- [ ] 6. Commit and push the changes to your GitHub repository. If all has gone well, your “index.html” file should look the same as before, but the code in "scripts.js" will look a whole lot more complicated. It’s also much more stable and ready to grow into a real app!

- [ ] 7. Submit the link to your GitHub repository here. Feel free to share additional thoughts or ask questions on your submissions page.

### Bonus Task

- [ ] If you’re feeling truly adventurous, you can take a look at how the `filter()` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) works and create a whole new public function for `pokemonRepository` that allows you to find specific Pokémon only by name.

**Comment by raheebwa** [comment]
Hey man, when you can, checkout this https://www.hackerrank.com. Its a good way for you to practice the basics

**Comment by rmoise** [comment]
Awesome, thanks for sharing! Will check this out.
